/***
 * Excerpted from "The Definitive ANTLR 4 Reference",
 * published by The Pragmatic Bookshelf.
 * Copyrights apply to this code. It may not be used to create training material, 
 * courses, books, articles, and the like. Contact us if you are in doubt.
 * We make no guarantees that this code is fit for any purpose. 
 * Visit http://www.pragmaticprogrammer.com/titles/tpantlr2 for more book information.
 ***/
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.misc.MultiMap;
import org.antlr.v4.runtime.misc.OrderedHashSet;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Set;

public class FsmProcess {

	static StringBuilder buf;

	static class Graph {
		// I'm using org.antlr.v4.runtime.misc: OrderedHashSet, MultiMap
		Set<String> nodes = new OrderedHashSet<String>(); // list of functions
		MultiMap<String, String> edges = // caller->callee
		new MultiMap<String, String>();

		public void edge(String source, String target) {
			edges.map(source, target);
		}

		public String toString() {
			return "edges: " + edges.toString() + ", functions: " + nodes;
		}
	 }
	/////////////////////////////////////////////////////////////////
	static class FunctionListener extends FsmBaseListener {
		Graph graph = new Graph();
		// String currentFunctionName = null;
		int cptStates = 0;
		int nbActionsInState;
		int nbActionsInTransition;
		Boolean inState = false; // set to true when inside a state, false  elsewhere
		Boolean inTransition = false; // set to true when inside a transistion,false elsewhere
		Boolean transitionIsReset=false;
		Boolean inAction = false; // set to true when inside an action, false elsewhere
		Boolean conditionDefined;
		String currentStateName = null;
		String actionType;
		String actionName;
		String actionExpression;
		String conditionName;
		////////////////////////////////////////////////////////////////
		public void enterReset_transition(FsmParser.Reset_transitionContext ctx)
		{			
			transitionIsReset=true;
			inTransition = true;
			conditionDefined=false;
			conditionName="1"; //default
			nbActionsInTransition=0;
			buf.append("    	node [shape=box] ");
			buf.append("    	emptystateforreset");
			buf.append(currentStateName);
			buf.append("[shape=box, style=\"invis\" ];\n");
			buf.append("    	emptystateforreset");
			buf.append(currentStateName);
 			buf.append(" -> ");
			buf.append(ctx.children.get(1).getText());
		}
		////////////////////////////////////////////////////////////////		
		public 	void exitReset_transition(FsmParser.Reset_transitionContext ctx)
		{
			inTransition = false;
			if (nbActionsInTransition==0) //the table and condition have not yet been generated by the first action
			{
				buf.append("[style=\"dashed\", shape=box, label=  <<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\"> <TR>   <TD COLSPAN=\"1\">");
				buf.append(conditionName);
				buf.append("</TD> </TR>");
			}
			buf.append("  </TABLE>>  ];\n");	
		}
		////////////////////////////////////////////////////////////////
		public void  enterCondition(FsmParser.ConditionContext ctx){
			conditionDefined=true;
			//ca vire les espaces
			//conditionName=ctx.getText();
			//System.out.println("conditionName:");
			//System.out.println(conditionName);
			conditionName="";
		    int nbChildren= ctx.getChildCount();
		    for (int n=0;n<nbChildren;n++)
		    {
		    	conditionName+=ctx.children.get(n).getText();
		    	if (n!=nbChildren-1)
		    		conditionName+=" ";
		    }
		}
		////////////////////////////////////////////////////////////////
		public 	void exitCondition(FsmParser.ConditionContext ctx){
	 	}
		////////////////////////////////////////////////////////////////
		public void enterTransition(FsmParser.TransitionContext ctx) {
			transitionIsReset=false;
			inTransition = true;
			conditionDefined=false;
			conditionName="1"; //default
			nbActionsInTransition=0;
			buf.append("    	");
			buf.append(ctx.children.get(0).getText());
			buf.append(" -> ");
			buf.append(ctx.children.get(2).getText());
		}
		////////////////////////////////////////////////////////////////
		public void exitTransition(FsmParser.TransitionContext ctx) {
			inTransition = false;
			if (nbActionsInTransition==0) //the table and condition have not yet been generated by the first action
			{
				buf.append("[shape=box, label=  <<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\"> <TR>   <TD COLSPAN=\"1\">");
				buf.append(conditionName);
				buf.append("</TD> </TR>");
			}
			buf.append("  </TABLE>>  ];\n");
		}
		////////////////////////////////////////////////////////////////
		public void enterAction_expression(FsmParser.Action_expressionContext ctx) {
			if (inState || inTransition) {
				actionExpression = ctx.children.get(0).getText();
			}
		}	
		////////////////////////////////////////////////////////////////
		public void exitAction_expression(FsmParser.Action_expressionContext ctx) {
		}
		////////////////////////////////////////////////////////////////
		public void enterAction_id(FsmParser.Action_idContext ctx) {
			if (inState || inTransition )
			{
				actionName = ctx.children.get(0).getText();
			}
 		}
		////////////////////////////////////////////////////////////////
		public void exitAction_id(FsmParser.Action_idContext ctx) {
		}
		////////////////////////////////////////////////////////////////
		public void enterAction_type(FsmParser.Action_typeContext ctx) {
			actionType = ctx.children.get(0).getText();
		}
		////////////////////////////////////////////////////////////////
		public void exitAction_type(FsmParser.Action_typeContext ctx) {
		}
		////////////////////////////////////////////////////////////////
		public void enterAction(FsmParser.ActionContext ctx) {
			actionType = "I"; // default value if not specified
			actionName = "";
			actionExpression = "";
			inAction = true; 
			if (inState) { 
				nbActionsInState++;
				if (nbActionsInState == 1) {
					buf.append("//Action on state:\n");
					buf.append("    	stateaction");
					buf.append(currentStateName);
					buf.append("  [shape=box,label=  ");
					buf.append(" <<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\">\n");
				}
			}
			else if (inTransition) { 
				nbActionsInTransition++;
				if (nbActionsInTransition == 1) 
				{ 
					buf.append("[");
					if (transitionIsReset==true)
						buf.append(" style=\"dashed\", ");
					buf.append("shape=box, label=  <<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\"> <TR>   <TD COLSPAN=\"2\">");
					buf.append(conditionName);
					buf.append("</TD> </TR>");
				}				
			}
		}
		////////////////////////////////////////////////////////////////
		public void exitAction(FsmParser.ActionContext ctx) {
			inAction = false;
			if (inState || inTransition) 
			{
				buf.append("<TR><TD>");
				buf.append(actionType);
				buf.append("</TD><TD>");
				buf.append(actionName);
				if (actionExpression != "") 
				{
					buf.append("=");
					buf.append(actionExpression);
				}
				buf.append("</TD> </TR>");
			}
		}	
		////////////////////////////////////////////////////////////////
		public void enterState(FsmParser.StateContext ctx) {
			cptStates++;
			inState = true;
			buf.append("    	");
			currentStateName = ctx.children.get(0).getText();
			buf.append(currentStateName);
			if (cptStates == 1)
				buf.append(" [shape=doublecircle];\n");
			else
				buf.append(" [shape=circle];\n");
			nbActionsInState = 0;
			// is there some action on this states
			/*
			 * int nbChildren= ctx.getChildCount();
			 * System.out.print("nbChildren:   ");
			 * System.out.println(nbChildren); for (int i=0;i<nbChildren;i++) {
			 * System.out.print(ctx.children.get(i).getText());
			 * System.out.print("   "); }
			 * System.out.println(ctx.getText());
			 */
		}
		/////////////////////////////////////////////////////////////////
		public void exitState(FsmParser.StateContext ctx) {
		// System.out.println("exit state");
		inState = false;
		if (nbActionsInState != 0) 
			{
			buf.append("</TABLE>>  ];\n");
			buf.append("//attach the action on the state\n    	");
			buf.append(currentStateName);
			buf.append(" ->");
			buf.append("stateaction");
			buf.append(currentStateName);
			buf.append("  [arrowhead=none]     ;\n");
			}
		}
		/////////////////////////////////////////////////////////////////
	}
	/////////////////////////////////////////////////////////////////
	public static void main(String[] args) throws Exception {
		String inputFile = null;
		if (args.length > 0)
			inputFile = args[0];
		InputStream is = System.in;
		if (inputFile != null) {
			is = new FileInputStream(inputFile);
		}
		ANTLRInputStream input = new ANTLRInputStream(is);
		FsmLexer lexer = new FsmLexer(input);
		CommonTokenStream tokens = new CommonTokenStream(lexer);
		FsmParser parser = new FsmParser(tokens);
		parser.setBuildParseTree(true);
		ParseTree tree = parser.file();
		// show tree in text form
		// System.out.println(tree.toStringTree(parser));

		ParseTreeWalker walker = new ParseTreeWalker();
		FunctionListener collector = new FunctionListener();

		buf = new StringBuilder();
		buf.append("///////////////////////////////////////////////////////////////////////////////////////////////////////////\n");
		buf.append("// Finite State Machine .dot diagram autogenerated by FsmProcess B. VANDEPORTAELE LAAS/CNRS 2016\n");
		buf.append("///////////////////////////////////////////////////////////////////////////////////////////////////////////\n");
		buf.append("digraph finite_state_machine {\n");
		buf.append("    	rankdir=LR;\n");
		buf.append("    	size=\"10\";\n");
		buf.append("///////////////////////////////////////////////////////////////////////////////////////////////////////////\n");
		walker.walk(collector, tree);
		// pour affichage en chaine
		// System.out.println(collector.graph.toString());
		// pour affichage en .DOT
		// System.out.println(collector.graph.toDOT());

		// Here's another example that uses StringTemplate to generate output
		// System.out.println(collector.graph.toST().render());

		buf.append("}\n");
		System.out.println(buf.toString());
	}
}
